### ISSUE TITLE
Carriage return/new line does not auto-indent

### ISSUE THREAD

**Issue by aarongodin** [jimmyhchan/dustjs.vim#6]
Each time I hit enter I'm taken directly to the top of the new line, rather than the next line being automatically indented to be nested within parent tags.

For example, when I type `{#users}` and hit enter, I would expect the next line to be a single indentation further than the front of the previous line.

**Comment by aarongodin** [comment]
Actually I bet this is the reason that issue #3 is being reported.

**Comment by jimmyhchan** [comment]
Hey thanks for reporting! It's been a long time since I've looked at this code. 

I'm looking at how the vim mustache plugin is doing it and found https://github.com/juvenn/mustache.vim/pull/11/files

seems this could work here as well.

**Comment by aarongodin** [comment]
Nice! I was doing some research in the mean time and had figured including
the HTML indentation from vims runtime was the way to go. I can put it
together and PR, unless you'd prefer to work on it.

**Comment by aarongodin** [comment]
Haha, I read that pull sort of quickly. I see they actually removed that and are using "matchit"? (will have to research that)
